### PR TITLE
Move trackviewer to current dependencies and do small refresh

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The changes in this pull request are mainly:
- Move buildsystem to maven (untie it from the IDE)
- Allow using GPX tracks as input
- dynamically generate JAXB code at build time (remove static code from repository)
- moderate code cleanup
  - reformatted to java code style
  - introduction of diamond operator
  - fix wrong assumption in gpx parsing (elevation can be missing)
- add dependencies on current version of jxmapviewer and org.json (remove source copy from build)

I'm not sure whether I'll do more with this, but I was looking through my trackfiles and replaced my own miniviewer with trackviewer.

Could you please add a license to this? LGPLv3 as jxmapviewer2 would look suitable.

### CODE REVIEW

**Comment by msteiger** [comment]
Thank you for your contribution. I will have a look soon (hopefully beginning of next week).I'd prefer Apache2 as license, if possible.

**Comment by msteiger** [comment]
I started reviewing this, but need more time. Will try to finish it after the weekend.

**Comment by matthiasblaesing** [comment]
With regard to the license I'm absolutely in agreement with choosing APLv2.

**Comment by msteiger** [comment]
Looks good to me. Thank you!

**Pull request merged**
